# Generated by Django 4.1 on 2022-09-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(choices=[('1', 'Family_Size'), ('2', 'Hungry_Size'), ('3', 'Big_Size'), ('4', 'Middle_Size'), ('5', 'Small_Size')], max_length=20),
        ),
    ]
