# Generated by Django 4.1 on 2022-09-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_size_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(choices=[('Pesto', 'Pesto'), ('Tomatoes', 'Tomatoes'), ('Cheese', 'Cheese'), ('Pepperoni', 'Pepperoni'), ('Olive', 'Olive')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(choices=[('Pesto', 'Pesto'), ('Tomatoes', 'Tomatoes'), ('Cheese', 'Cheese'), ('Pepperoni', 'Pepperoni'), ('Olive', 'Olive')], max_length=100),
        ),
    ]
